### Load libraries 
library(ape)
library(caper)
library(tibble)
library(dplyr)
library(ggplot2)
library(ggtree)
library(ggtreeExtra)
library(ggnewscale)

### Read in pre-made tree downloaded from MGYG FTP site
tree <- read.tree("bac120_iqtree.nwk")

### Read in trait data generated by trait_data.py
traits <- read.csv("functional_trait_data_final.csv")

### Prune tree so it only contains detected genera
pruned_tree <- keep.tip(tree, traits$ID)
tip_map <- setNames(traits$Genus, traits$ID)
pruned_tree$tip.label <- tip_map[pruned_tree$tip.label]
rownames(traits) <- traits$Genus
traits <- traits |> rownames_to_column(var = "label")
common <- intersect(pruned_tree$tip.label, traits$label)


plotTree <- keep.tip(pruned_tree, common)
plotTraits <- traits %>%
    filter(label %in% common) %>%
    arrange(match(label, plotTree$tip.label))

### If spectral count is less than 10, don't plot average enrichment
plotTraits <- plotTraits %>%
    mutate(Enrichment = ifelse(Labeled_Spectral_Count < 10, 0, Enrichment))

tree <- ggtree(plotTree, layout = "rectangular", branch.length = "none") %<+% plotTraits +
    geom_tiplab(aes(label = label), size = 3.5, offset = 1) +

    # 1. Total Spectral Count
    geom_fruit(
        geom = geom_tile,
        mapping = aes(y = label, x = "Total\nSC", fill = Total_Spectral_Count),
        width = 1.6, offset = 0.5, color = "grey80", linewidth = 0.2
    ) +
    scale_fill_gradient(low = "white", high = "darkmagenta",
                    name = "Total\nSpectral Count",
                    limits = c(0, 500),
                    breaks = c(0, 200, 400, 600),
                    guide = guide_colorbar(order = 1),
                    oob = scales::squish) +

    # 2. Labeled Spectral Count
    new_scale_fill() +
    geom_fruit(
        geom = geom_tile,
        mapping = aes(y = label, x = "Labeled\nSC", fill = Labeled_Spectral_Count),
        width = 1.6, offset = 0.05, color = "grey80", linewidth = 0.2
    ) +
    scale_fill_gradient(low = "white", high = "forestgreen",
                    name = "Labeled\nSpectral Count",
                    breaks = c(0, 50,100, 150),
                    limits = c(0, 125),
                    guide = guide_colorbar(order = 2),
                    oob = scales::squish) +

    # 3. Enrichment
    new_scale_fill() +
    geom_fruit(
        geom = geom_tile,
        mapping = aes(y = label, x = "Enrichment", fill = Enrichment),
        width = 1.6, offset = 0.05, color = "grey80", linewidth = 0.2
    ) +
    scale_fill_gradient(low = "white", high = "cornflowerblue",
                        name = "Average\nEnrichment (%)",
                        limits = c(0, 100),
                        breaks = c(0, 50, 100),
                        guide = guide_colorbar(order = 3),
                        oob = scales::squish) +

    # 4. Butyrate kinase
    new_scale_fill() +
    geom_fruit(
        geom = geom_tile,
        mapping = aes(y = label, x = "Butyrate\nKinase", fill = butyrate.kinase),
        width = 1.6, offset = 0.05, color = "grey80", linewidth = 0.2
    ) +
    scale_fill_gradient(low = "white", high = "goldenrod",
                        name = "Butyrate kinase",
                        limits = c(0, NA),
                        guide = guide_colorbar(order = 4)) +

    # 5. Butyryl-CoA dehydrogenase
    new_scale_fill() +
    geom_fruit(
        geom = geom_tile,
        mapping = aes(y = label, x = "Butyryl-\nCoA DH", fill = butyryl.CoA.dehydrogenase),
        width = 1.6, offset = 0.05, color = "grey80", linewidth = 0.2
    ) +
    scale_fill_gradient(low = "white", high = "firebrick1",
                        name = "Butyryl-CoA\ndehydrogenase",
                        limits = c(0, NA),
                        guide = guide_colorbar(order = 5)) +

    # 6. 3-hydroxybutyryl-CoA dehydrogenase
    new_scale_fill() +
    geom_fruit(
        geom = geom_tile,
        mapping = aes(y = label, x = "3-OH\nButyryl-CoA DH", fill = X3.hydroxybutyryl.CoA.dehydrogenase),
        width = 1.6, offset = 0.05, color = "grey80", linewidth = 0.2
    ) +
    scale_fill_gradient(low = "white", high = "coral4",
                        name = "3-hydroxybutyryl-\nCoA dehydrogenase",
                        limits = c(0, NA),
                        guide = guide_colorbar(order = 6)) +

    theme_tree2() +
    theme(
        legend.position   = "right",
        legend.key.size   = unit(0.3, "cm"),
        legend.text       = element_text(size = 8),
        legend.title      = element_text(size = 8, face = "bold"),
        legend.box        = "vertical",
        legend.spacing.y  = unit(0.1, "cm"),
        plot.margin       = margin(5, 160, 5, 20)
    ) +
    labs(title = "Phylogenetic Tree of All Detected Genera")

tree